### ISSUE TITLE
ImportError: cannot import name IndexMarker (version 20.4.1)

### ISSUE THREAD

**Issue by network-dave** [CiscoTestAutomation/genieparser#160]
Hi, there seems to be an issue with the dq module that is called when parsing a device, since upgrading Genie to 20.4.1 :

ImportError: cannot import name IndexMarker

Traceback (most recent call last):
  File "./parse_show_interface_status.py", line 7, in <module>
    from genie.conf.base import Device
  File "/mnt/c/Users/id865890/Documents/Python/venvs/genie-parsers/lib/python3.8/site-packages/genie/conf/__init__.py", line 16, in <module>
    from .main import Genie
  File "src/genie/conf/main.py", line 4, in init genie.conf.main
  File "/mnt/c/Users/id865890/Documents/Python/venvs/genie-parsers/lib/python3.8/site-packages/genie/conf/base/__init__.py", line 4, in <module>
    from .device import Device
  File "src/genie/conf/base/device.py", line 12, in init genie.conf.base.device
  File "src/genie/ops/utils.py", line 6, in init genie.ops.utils
  File "/mnt/c/Users/id865890/Documents/Python/venvs/genie-parsers/lib/python3.8/site-packages/genie/utils/__init__.py", line 13, in <module>
    from .dq import Dq
  File "src/genie/utils/dq.py", line 6, in init genie.utils.dq
I

**Comment by network-dave** [comment]
Relevant code snippet :

    device = Device(name=device_name, os=args.os)
    device.custom.abstraction = {"order": ["os"]}
    parsed_objects = device.parse(parser, output=data)

**Comment by xiaoxinz-cisco** [comment]
Hi @network-dave ,

Could you please check the version you're using? The latest version is `v20.5`, below command would upgrade the package:
- `pip install --upgrade pyats[full]`

Let me know if it works.

Thanks,
Irene

**Comment by network-dave** [comment]
Hello Irene, will upgrade to 20.5 and report back to you asap. Thank you !

**Comment by network-dave** [comment]
Everything seems good so far with upgrading to 20.5 

Thanks again !
